/**
 * @author [Tristan Valcke]{@link https://github.com/Itee}
 * @license [BSD-3-Clause]{@link https://opensource.org/licenses/BSD-3-Clause}
 */

import { Color } from 'three-full'

const Colors = {
    Black:                new Color( '#000000' ),
    Navy:                 new Color( '#000080' ),
    DarkBlue:             new Color( '#00008b' ),
    MediumBlue:           new Color( '#0000cd' ),
    Blue:                 new Color( '#0000ff' ),
    DarkGreen:            new Color( '#006400' ),
    Green:                new Color( '#008000' ),
    Teal:                 new Color( '#008080' ),
    DarkCyan:             new Color( '#008b8b' ),
    DeepSkyBlue:          new Color( '#00bfff' ),
    DarkTurquoise:        new Color( '#00ced1' ),
    MediumSpringGreen:    new Color( '#00fa9a' ),
    Lime:                 new Color( '#00ff00' ),
    SpringGreen:          new Color( '#00ff7f' ),
    Aqua:                 new Color( '#00ffff' ),
    Cyan:                 new Color( '#00ffff' ),
    MidnightBlue:         new Color( '#191970' ),
    DodgerBlue:           new Color( '#1e90ff' ),
    LightSeaGreen:        new Color( '#20b2aa' ),
    ForestGreen:          new Color( '#228b22' ),
    SeaGreen:             new Color( '#2e8b57' ),
    DarkSlateGray:        new Color( '#2f4f4f' ),
    DarkSlateGrey:        new Color( '#2f4f4f' ),
    LimeGreen:            new Color( '#32cd32' ),
    MediumSeaGreen:       new Color( '#3cb371' ),
    Turquoise:            new Color( '#40e0d0' ),
    RoyalBlue:            new Color( '#4169e1' ),
    SteelBlue:            new Color( '#4682b4' ),
    DarkSlateBlue:        new Color( '#483d8b' ),
    MediumTurquoise:      new Color( '#48d1cc' ),
    Indigo:               new Color( '#4b0082' ),
    DarkOliveGreen:       new Color( '#556b2f' ),
    CadetBlue:            new Color( '#5f9ea0' ),
    CornflowerBlue:       new Color( '#6495ed' ),
    RebeccaPurple:        new Color( '#663399' ),
    MediumAquaMarine:     new Color( '#66cdaa' ),
    DimGray:              new Color( '#696969' ),
    DimGrey:              new Color( '#696969' ),
    SlateBlue:            new Color( '#6a5acd' ),
    OliveDrab:            new Color( '#6b8e23' ),
    SlateGray:            new Color( '#708090' ),
    SlateGrey:            new Color( '#708090' ),
    LightSlateGray:       new Color( '#778899' ),
    LightSlateGrey:       new Color( '#778899' ),
    MediumSlateBlue:      new Color( '#7b68ee' ),
    LawnGreen:            new Color( '#7cfc00' ),
    Chartreuse:           new Color( '#7fff00' ),
    Aquamarine:           new Color( '#7fffd4' ),
    Maroon:               new Color( '#800000' ),
    Purple:               new Color( '#800080' ),
    Olive:                new Color( '#808000' ),
    Gray:                 new Color( '#808080' ),
    Grey:                 new Color( '#808080' ),
    SkyBlue:              new Color( '#87ceeb' ),
    LightSkyBlue:         new Color( '#87cefa' ),
    BlueViolet:           new Color( '#8a2be2' ),
    DarkRed:              new Color( '#8b0000' ),
    DarkMagenta:          new Color( '#8b008b' ),
    SaddleBrown:          new Color( '#8b4513' ),
    DarkSeaGreen:         new Color( '#8fbc8f' ),
    LightGreen:           new Color( '#90ee90' ),
    MediumPurple:         new Color( '#9370db' ),
    DarkViolet:           new Color( '#9400d3' ),
    PaleGreen:            new Color( '#98fb98' ),
    DarkOrchid:           new Color( '#9932cc' ),
    YellowGreen:          new Color( '#9acd32' ),
    Sienna:               new Color( '#a0522d' ),
    Brown:                new Color( '#a52a2a' ),
    DarkGray:             new Color( '#a9a9a9' ),
    DarkGrey:             new Color( '#a9a9a9' ),
    LightBlue:            new Color( '#add8e6' ),
    GreenYellow:          new Color( '#adff2f' ),
    PaleTurquoise:        new Color( '#afeeee' ),
    LightSteelBlue:       new Color( '#b0c4de' ),
    PowderBlue:           new Color( '#b0e0e6' ),
    FireBrick:            new Color( '#b22222' ),
    DarkGoldenRod:        new Color( '#b8860b' ),
    MediumOrchid:         new Color( '#ba55d3' ),
    RosyBrown:            new Color( '#bc8f8f' ),
    DarkKhaki:            new Color( '#bdb76b' ),
    Silver:               new Color( '#c0c0c0' ),
    MediumVioletRed:      new Color( '#c71585' ),
    IndianRed:            new Color( '#cd5c5c' ),
    Peru:                 new Color( '#cd853f' ),
    Chocolate:            new Color( '#d2691e' ),
    Tan:                  new Color( '#d2b48c' ),
    LightGray:            new Color( '#d3d3d3' ),
    LightGrey:            new Color( '#d3d3d3' ),
    Thistle:              new Color( '#d8bfd8' ),
    Orchid:               new Color( '#da70d6' ),
    GoldenRod:            new Color( '#daa520' ),
    PaleVioletRed:        new Color( '#db7093' ),
    Crimson:              new Color( '#dc143c' ),
    Gainsboro:            new Color( '#dcdcdc' ),
    Plum:                 new Color( '#dda0dd' ),
    BurlyWood:            new Color( '#deb887' ),
    LightCyan:            new Color( '#e0ffff' ),
    Lavender:             new Color( '#e6e6fa' ),
    DarkSalmon:           new Color( '#e9967a' ),
    Violet:               new Color( '#ee82ee' ),
    PaleGoldenRod:        new Color( '#eee8aa' ),
    LightCoral:           new Color( '#f08080' ),
    Khaki:                new Color( '#f0e68c' ),
    AliceBlue:            new Color( '#f0f8ff' ),
    HoneyDew:             new Color( '#f0fff0' ),
    Azure:                new Color( '#f0ffff' ),
    SandyBrown:           new Color( '#f4a460' ),
    Wheat:                new Color( '#f5deb3' ),
    Beige:                new Color( '#f5f5dc' ),
    WhiteSmoke:           new Color( '#f5f5f5' ),
    MintCream:            new Color( '#f5fffa' ),
    GhostWhite:           new Color( '#f8f8ff' ),
    Salmon:               new Color( '#fa8072' ),
    AntiqueWhite:         new Color( '#faebd7' ),
    Linen:                new Color( '#faf0e6' ),
    LightGoldenRodYellow: new Color( '#fafad2' ),
    OldLace:              new Color( '#fdf5e6' ),
    Red:                  new Color( '#ff0000' ),
    Fuchsia:              new Color( '#ff00ff' ),
    Magenta:              new Color( '#ff00ff' ),
    DeepPink:             new Color( '#ff1493' ),
    OrangeRed:            new Color( '#ff4500' ),
    Tomato:               new Color( '#ff6347' ),
    HotPink:              new Color( '#ff69b4' ),
    Coral:                new Color( '#ff7f50' ),
    DarkOrange:           new Color( '#ff8c00' ),
    LightSalmon:          new Color( '#ffa07a' ),
    Orange:               new Color( '#ffa500' ),
    LightPink:            new Color( '#ffb6c1' ),
    Pink:                 new Color( '#ffc0cb' ),
    Gold:                 new Color( '#ffd700' ),
    PeachPuff:            new Color( '#ffdab9' ),
    NavajoWhite:          new Color( '#ffdead' ),
    Moccasin:             new Color( '#ffe4b5' ),
    Bisque:               new Color( '#ffe4c4' ),
    MistyRose:            new Color( '#ffe4e1' ),
    BlanchedAlmond:       new Color( '#ffebcd' ),
    PapayaWhip:           new Color( '#ffefd5' ),
    LavenderBlush:        new Color( '#fff0f5' ),
    SeaShell:             new Color( '#fff5ee' ),
    Cornsilk:             new Color( '#fff8dc' ),
    LemonChiffon:         new Color( '#fffacd' ),
    FloralWhite:          new Color( '#fffaf0' ),
    Snow:                 new Color( '#fffafa' ),
    Yellow:               new Color( '#ffff00' ),
    LightYellow:          new Color( '#ffffe0' ),
    Ivory:                new Color( '#fffff0' ),
    White:                new Color( '#ffffff' )
}

Colors.UI = {
    Default:     Colors.Fuchsia,
    Intersected: Colors.PeachPuff,
    Selected:    Colors.DarkOrange,
    Active:      Colors.YellowGreen,
    Inactive:    Colors.LightCyan,
    Enabled:     Colors.Lavender,
    Disabled:    Colors.Grey
}

export {
    Colors
}
